#數據庫配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/books
    username: root
    password: 1234
#Mybatis
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
#開啟spring事务管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug